In [2]:
#Run this cell if you use Colab, otherwise, please IGNORE it!
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# **Week 2 Applied Session: Data Discovery & Collection (Alternative Solutions)**


Here we provide an alternative solution to avoid the unfold data part.

This includes:

Step 1. Inspect raw data <br>
Step 2. Tidy up the raw data file <br>
Step 3. Read data to a pandas dataframe <br>
Step 4. Transpose each observation from long to wide and append all observations to a master dataframe


Before we start we need to check the Python version:

In [1]:
import sys
print (sys.version_info)

sys.version_info(major=3, minor=11, micro=11, releaselevel='final', serial=0)

The code is developed using: Python 2.7.12 :: Anaconda 4.1.1 (64-bit).

We are going to use the following library:

In [4]:
import pandas as pd
# to make the code compatable with python 3
from __future__ import print_function, division

## Step 1 inspect raw data

A lot can be learned from looking at the raw data. As the file is not large, we will first read the data file and have a quick look.

In [5]:
#Please use your own local file url to replace the location below, OR use the Colab and keep it unchanged.
with open('/content/drive/Shareddrives/FIT5196_S2_2026/Week2/AirCrashes_raw.csv','r') as infile:
    text = infile.read()
text

"\nIncident American Airlines Flight 11 involving a Boeing 767-223ER in 2001\nCasualties,Extremely High\nTotal Dead,1692\nCrew,11\nPassengers,81\nGround,1600\nNotes,No survivors\nType,INH\nReason,Attack\nLocation,New York - New York - US\nCountry,US\nPhase,ENR\nDate,2001-09-11\nLatitude,40.7143528\nLongitude,-74.0059731\nCircumstances,Good Visibility by Day\n\nIncident United Airlines Flight 175 involving a Boeing 767-222 in 2001\nCasualties,Extremely High\nTotal Dead,965\nCrew,9\nPassengers,56\nGround,900\nNotes,No survivors\nType,INH\nReason,Attack\nLocation,New York - New York - US\nCountry,USA\nPhase,ENR\nDate,2001-09-11\nLatitude,40.7143528\nLongitude,-74.0059731\nCircumstances,Good Visibility by Day\n\nIncident Pan Am Flight 1736 and KLM Flight 4805 involving a Boeing 747-121 and\xa0Boeing 747-206B in 1977\nCasualties,Extremely High\nTotal Dead,583\nCrew,23\nPassengers,560\nGround,0\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Tenerife - Spain\nCountry,Spain\nPhase,TOF\nDate,1977-03-27\nLatitude,28.2915637\nLongitude,-16.6291304\nCircumstances,Bad Visibility by Day\n\nIncident Japan Airlines Flight 123 involving a Beoing 747SR-46 in 1985\nCasualties,Extremely High\nTotal Dead,520\nCrew,15\nPassengers,505\nGround,0\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Ueno - Japan\nCountry,Japan\nPhase,ENR\nDate,1985-08-12\nLatitude,35.7089461\nLongitude,139.7742683\nCircumstances,Bad Visibility by Night\n\nIncident Saudi Arabian Flight 763 and involving a Boeing 747-168B and\xa0Ilyushin Il-76TD in 1996\nCasualties,Extremely High\nTotal Dead,349\nCrew,33\nPassengers,316\nGround,0\nNotes,No survivors\nType,   \nReason,Accident\nLocation,Charkhi Dadri - India\nCountry,India\nPhase,ENR\nDate,1996-11-12\nLatitude,28.6\nLongitude,76.2667\nCircumstances,Bad Visibility by Night\n\nIncident Turkish Airlines Flight 981 involving a McDonnell Douglas DC-10-10 in 1974\nCasualties,Extremely High\nTotal Dead,346\nCrew,11\nPassengers,335\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Fontaine-Chaalis - France\nCountry,France\nPhase,ENR\nDate,1974-03-03\nLatitude,49.171795\nLongitude,2.684157\nCircumstances,Bad Visibility by Night\n\nIncident Air India Flight 182 involving a Boeing 747-237B in 1985\nCasualties,Extremely High\nTotal Dead,329\nCrew,22\nPassengers,307\nGround,0\nNotes,No survivors\nType,INB\nReason,Attack\nLocation,Atlantic Ocean - Cork - Ireland\nCountry,Ireland\nPhase,ENR\nDate,1985-06-23\nLatitude,51.8968917\nLongitude,-8.4863157\nCircumstances,Bad Visibility by Night\n\nIncident Saudia Flight 163 involving a Lockheed L-1011-200 TriStar in 1980\nCasualties,Extremely High\nTotal Dead,301\nCrew,14\nPassengers,287\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Riyadh - Saudi Arabia\nCountry,Saudi Arabia\nPhase,ENR\nDate,1980-08-19\nLatitude,24.7116667\nLongitude,46.7241667\nCircumstances,Bad Visibility by Night\n\nIncident Iran Air Flight 655 involving a Airbus A300B2-203 in 1988\nCasualties,Extremely High\nTotal Dead,290\nCrew,16\nPassengers,274\nGround,0\nNotes,No survivors\nType,EXG\nReason,Attack\nLocation,Strait of Hormuz - Iran\nCountry,Iran\nPhase,ENR\nDate,1988-07-03\nLatitude,26.5944754\nLongitude,56.4719928\nCircumstances,Bad Visibility by Night\n\nIncident Iranian Air Force (15-2280) involving a Ilyushin Il-76MD in 2003\nCasualties,Extremely High\nTotal Dead,275\nCrew,18\nPassengers,257\nGround,0\nNotes,No survivors\nType,MIL\nReason,Accident\nLocation,Kerman - Iran\nCountry,Iran\nPhase,ENR\nDate,2003-02-19\nLatitude,30.28027\nLongitude,57.06702\nCircumstances,Bad Visibility by Night\n\nIncident American Airlines Flight 191 involving a McDonnell Douglas DC-10-10 in 1979\nCasualties,Extremely High\nTotal Dead,273\nCrew,13\nPassengers,258\nGround,2\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Des Plaines - Illinois - US\nCountry,US\nPhase,TOF\nDate,1979-05-25\nLatitude,42.0333623\nLongitude,-87.8833991\nCircumstances,Bad Visibility by Night\n\nIncident Pan Am Flight 103 involving a Boeing 747-121 in 1988\nCasualties,Extremely High\nTotal Dead,270\nCrew,16\nPassengers,243\nGround,11\nNotes,No survivors\nType,INB\nReason,Attack\nLocation,Lockerbie - Scotland - UK\nCountry,UK\nPhase,ENR\nDate,1988-12-21\nLatitude,55.122245\nLongitude,-3.349008\nCircumstances,Bad Visibility by Night\n\nIncident Korean Air Lines Flight 007 involving a Boeing 747-230B in 1983\nCasualties,Extremely High\nTotal Dead,269\nCrew,23\nPassengers,246\nGround,0\nNotes,No survivors\nType,EXS\nReason,Attack\nLocation,Sea of Japan - Moneron Island - Russia\nCountry,Russia\nPhase,ENR\nDate,1983-09-01\nLatitude,46.25\nLongitude,141.2333333\nCircumstances,Bad Visibility by Night\n\nIncident American Airlines Flight 587 involving a Airbus A300B4-605R in 2001\nCasualties,Extremely High\nTotal Dead,265\nCrew,9\nPassengers,251\nGround,5\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Belle Harbor - New York - US\nCountry,US\nPhase,ENR\nDate,2001-11-12\nLatitude,40.5759385\nLongitude,-73.8481906\nCircumstances,Bad Visibility by Night\n\nIncident China Airlines Flight 140 involving a Airbus A300B4-622R in 1994\nCasualties,Extremely High\nTotal Dead,264\nCrew,15\nPassengers,249\nGround,0\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Komaki - Japan\nCountry,Japan\nPhase,APR\nDate,1994-04-26\nLatitude,35.2903104\nLongitude,136.9109515\nCircumstances,Bad Visibility by Night\n\nIncident Nigeria Airways Flight 2120 involving a Douglas DC-8-61 in 1991\nCasualties,Extremely High\nTotal Dead,261\nCrew,14\nPassengers,247\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Jeddah - Saudi Arabia\nCountry,Saudi Arabia\nPhase,APR\nDate,1991-07-11\nLatitude,21.5433333\nLongitude,39.1727778\nCircumstances,Bad Visibility by Night\n\nIncident Air New Zealand Flight 901 involving a McDonnell Douglas DC-10-30 in 1979\nCasualties,Extremely High\nTotal Dead,257\nCrew,20\nPassengers,237\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Mt. Erebus - Antarctica\nCountry,Antarctica\nPhase,ENR\nDate,1979-11-28\nLatitude,-77.5310559\nLongitude,167.0757008\nCircumstances,Bad Visibility by Night\n\nIncident Arrow Air Flight 1285 involving a Douglas DC-8-63CF in 1985\nCasualties,Extremely High\nTotal Dead,256\nCrew,8\nPassengers,248\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Gander - NL. - Canada\nCountry,Canada\nPhase,ICL\nDate,1985-12-12\nLatitude,48.954408\nLongitude,-54.6103488\nCircumstances,Bad Visibility by Night\n\nIncident African Air (RA-26222) involving a Antonov An-32B in 1996\nCasualties,Extremely High\nTotal Dead,37\nCrew,0\nPassengers,0\nGround,237\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Kinshasa - DR Congo\nCountry,DR Congo\nPhase,ICL\nDate,1996-01-08\nLatitude,-4.3316667\nLongitude,15.3138889\nCircumstances,Bad Visibility by Night\n\nIncident Garuda Indonesia Flight 152 involving a Airbus A300B4-220 in 1997\nCasualties,Extremely High\nTotal Dead,234\nCrew,12\nPassengers,222\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Medan - Indonesia\nCountry,Indonesia\nPhase,APR\nDate,1997-09-26\nLatitude,3.585242\nLongitude,98.6755979\nCircumstances,Bad Visibility by Night\n\nIncident TWA Flight 800 involving a Boeing 747-131 in 1996\nCasualties,Extremely High\nTotal Dead,230\nCrew,18\nPassengers,212\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Atlantic Ocean - East Moriches - New York - US\nCountry,US\nPhase,ENR\nDate,1996-07-17\nLatitude,40.8050989\nLongitude,-72.7609336\nCircumstances,Bad Visibility by Night\n\nIncident Swissair Flight 111 involving a McDonnell Douglas MD-11 in 1998\nCasualties,Extremely High\nTotal Dead,229\nCrew,14\nPassengers,215\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Atlantic Ocean - Peggys Cove - N.S. - Canada\nCountry,Canada\nPhase,ENR\nDate,1998-09-02\nLatitude,44.4927778\nLongitude,-63.9175\nCircumstances,Bad Visibility by Day\n\nIncident Air France Flight 447 involving a Airbus A330-203 in 2009\nCasualties,Extremely High\nTotal Dead,228\nCrew,12\nPassengers,216\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Atlantic Ocean - Sao Pedro\nCountry,Sao Pedro\nPhase,ENR\nDate,2009-06-01\nLatitude,03.065833\nLongitude,-30.561667\nCircumstances,Bad Visibility by Night\n\nIncident Korean Air Flight 801 involving a Boeing 747-3B5 in 1997\nCasualties,Extremely High\nTotal Dead,228\nCrew,22\nPassengers,206\nGround,0\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Asan - Guam - US\nCountry,US\nPhase,APR\nDate,1997-08-06\nLatitude,13.4666808\nLongitude,144.7454685\nCircumstances,Bad Visibility by Night\n\nIncident China Airlines Flight 611 involving a Boeing 747-209B in 2002\nCasualties,Extremely High\nTotal Dead,225\nCrew,19\nPassengers,206\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Taiwan Strait - Penghu Islands - China\nCountry,China\nPhase,ENR\nDate,2002-05-25\nLatitude,23.5025\nLongitude,119.5052778\nCircumstances,Bad Visibility by Night\n\nIncident Lauda Air Flight 004 involving a Boeing 767-3Z9ER in 1991\nCasualties,Extremely High\nTotal Dead,223\nCrew,10\nPassengers,213\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Phu Toei National Park - Thailand\nCountry,Thailand\nPhase,ENR\nDate,1991-05-26\nLatitude,14.9413999\nLongitude,99.4490951\nCircumstances,Bad Visibility by Night\n\nIncident EgyptAir Flight 990 involving a Boeing 767-366ER in 1999\nCasualties,Extremely High\nTotal Dead,217\nCrew,15\nPassengers,202\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Atlantic Ocean - Nantucket - Massachusetts - US\nCountry,US\nPhase,ENR\nDate,1999-10-31\nLatitude,41.2834704\nLongitude,-70.099451\nCircumstances,Bad Visibility by Night\n\nIncident Air India Flight 855 involving a Boeing 747-237B in 1978\nCasualties,Extremely High\nTotal Dead,213\nCrew,23\nPassengers,190\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Arabian Sea -  Mumbai - India\nCountry,India\nPhase,ENR\nDate,1978-01-01\nLatitude,19.0759837\nLongitude,72.8776559\nCircumstances,Bad Visibility by Night\n\nIncident China Airlines Flight 676 involving a Airbus A300-622R in 1998\nCasualties,Extremely High\nTotal Dead,202\nCrew,14\nPassengers,182\nGround,7\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Dayuan - Taiwan - China\nCountry,China\nPhase,APR\nDate,1998-02-16\nLatitude,25.0492632\nLongitude,121.193945\nCircumstances,Bad Visibility by Night\n\nIncident Aeroflot Flight 7425 involving a Tupolev Tu-154B-2 in 1985\nCasualties,Extremely High\nTotal Dead,0\nCrew,9\nPassengers,191\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Uchkuduk - Uzbekistan\nCountry,Uzbekistan\nPhase,ENR\nDate,1985-07-10\nLatitude,42.1566667\nLongitude,63.5555556\nCircumstances,Bad Visibility by Night\n\nIncident TAM Airlines Flight 3054 involving a Airbus A320-233 in 2007\nCasualties,Extremely High\nTotal Dead,199\nCrew,6\nPassengers,181\nGround,12\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Sao Paulo - Brazil\nCountry,Brazil\nPhase,LDG\nDate,2007-07-17\nLatitude,-23.5489433\nLongitude,-46.6388182\nCircumstances,Bad Visibility by Night\n\nIncident Martinair Holland Flight 138 involving a Douglas DC-8-55F in 1974\nCasualties,Extremely High\nTotal Dead,191\nCrew,9\nPassengers,182\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Maskeliya - Sri Lanka\nCountry,Sri Lanka\nPhase,ENR\nDate,1974-12-04\nLatitude,6.8329294\nLongitude,80.5709256\nCircumstances,Bad Visibility by Night\n\nIncident American Airlines Flight 77 involving a Boeing 757-223 in 2001\nCasualties,Extremely High\nTotal Dead,189\nCrew,6\nPassengers,64\nGround,125\nNotes,No survivors\nType,INH\nReason,Attack\nLocation,Arlington - Virginia - US\nCountry,US\nPhase,ENR\nDate,2001-09-11\nLatitude,38.8799697\nLongitude,-77.1067698\nCircumstances,Bad Visibility by Day\n\nIncident Alas Nacionales Flight 301 involving a Boeing 757-225 in 1996\nCasualties,Extremely High\nTotal Dead,189\nCrew,13\nPassengers,176\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Atlantic Ocean - Puerto Plata - Dominican Republic\nCountry,Dominican Republic\nPhase,ENR\nDate,1996-02-06\nLatitude,19.7807686\nLongitude,-70.6871091\nCircumstances,Bad Visibility by Night\n\nIncident Alia Royal Jordanian (JY-AEE) involving a Boeing 707-321C in 1975\nCasualties,Extremely High\nTotal Dead,188\nCrew,7\nPassengers,181\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Tamri - Morocco\nCountry,Morocco\nPhase,ENR\nDate,1975-08-03\nLatitude,30.6981676\nLongitude,-9.8208632\nCircumstances,Bad Visibility by Night\n\nIncident LOT Flight 5055 involving a Ilyushin Il-62M in 1987\nCasualties,Extremely High\nTotal Dead,183\nCrew,11\nPassengers,172\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Warsaw - Poland\nCountry,Poland\nPhase,ENR\nDate,1987-05-09\nLatitude,52.2296756\nLongitude,21.0122287\nCircumstances,Bad Visibility by Night\n\nIncident Icelandic Airlines Flight LL 001 involving a Douglas DC-8 in 1978\nCasualties,Extremely High\nTotal Dead,183\nCrew,8\nPassengers,175\nGround,0\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Katunayake - Sri Lanka\nCountry,Sri Lanka\nPhase,APR\nDate,1978-11-15\nLatitude,7.1696231\nLongitude,79.8912813\nCircumstances,Bad Visibility by Night\n\nIncident Avianca Flight 011 involving a Boeing 747-283B in 1983\nCasualties,Extremely High\nTotal Dead,181\nCrew,\nPassengers,162\nGround,0\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Madrid - Spain\nCountry,Spain\nPhase,APR\nDate,1983-11-27\nLatitude,40.4167754\nLongitude,-3.7037902\nCircumstances,Bad Visibility by Night\n\nIncident Inex-Adria Aviopromet Flight 1308 involving a McDonnell Douglas MD-81 in 1981\nCasualties,Extremely High\nTotal Dead,180\nCrew,7\nPassengers,173\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Mt. San Pietro - Petreto-Bicchisano - Corsica - France\nCountry,France\nPhase,ENR\nDate,1981-12-01\nLatitude,41.7588889\nLongitude,8.9916667\nCircumstances,Bad Visibility by Night\n\nIncident Aeroflot Flight 3352 involving a Tupolev Tu-154 in 1984\nCasualties,Extremely High\nTotal Dead,178\nCrew,5\nPassengers,169\nGround,4\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Omsk - Russia\nCountry,Russia\nPhase,LDG\nDate,1984-10-11\nLatitude,54.9666667\nLongitude,73.3833333\nCircumstances,Bad Visibility by Night\n\nIncident Aeroflot/Moldovia (CCCP-65816) involving a Tupolev Tu-134A(both) in 1979\nCasualties,Extremely High\nTotal Dead,178\nCrew,13\nPassengers,165\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Saykyn - Kazakhstan\nCountry,Kazakhstan\nPhase,ENR\nDate,1979-08-11\nLatitude,48.8125\nLongitude,46.7636111\nCircumstances,Bad Visibility by Night\n\nIncident British Airways Flight 476 and involving a Hawker Siddeley Trident 3B\xa0and in 1976\nCasualties,Extremely High\nTotal Dead,177\nCrew,14\nPassengers,162\nGround,1\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Vrbovec - Croatia\nCountry,Croatia\nPhase,ENR\nDate,1976-09-10\nLatitude,45.8839523\nLongitude,16.416766\nCircumstances,Bad Visibility by Night\n\nIncident Surinam Airways Flight 764 involving a Douglas DC-8-62 in 1989\nCasualties,Extremely High\nTotal Dead,176\nCrew,9\nPassengers,167\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Paramaribo - Surinam\nCountry,Surinam\nPhase,APR\nDate,1989-06-07\nLatitude,5.823201\nLongitude,-55.16788\nCircumstances,Bad Visibility by Day\n\nIncident Nigeria Airways (JY-ADO) involving a Boeing 707-3D3C in 1973\nCasualties,Extremely High\nTotal Dead,176\nCrew,6\nPassengers,170\nGround,0\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Kano - Nigeria\nCountry,Nigeria\nPhase,LDG\nDate,1973-01-22\nLatitude,12\nLongitude,8.516667\nCircumstances,Bad Visibility by Day\n\nIncident Aeroflot Flight 217 involving a Ilyushin Il-62 in 1972\nCasualties,Extremely High\nTotal Dead,174\nCrew,10\nPassengers,164\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Moscow - Russia\nCountry,Russia\nPhase,APR\nDate,1972-10-13\nLatitude,55.755826\nLongitude,37.6173\nCircumstances,Bad Visibility by Day\n\nIncident Cubana de Aviación Flight 9646 involving a Ilyushin II-62M in 1989\nCasualties,Extremely High\nTotal Dead,171\nCrew,11\nPassengers,115\nGround,45\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Havana - Cuba\nCountry,Cuba\nPhase,ICL\nDate,1989-09-03\nLatitude,23.1168\nLongitude,-82.388557\nCircumstances,Bad Visibility by Day\n\nIncident Pulkovo Flight 612 involving a Tupolev Tu-154M in 2006\nCasualties,Extremely High\nTotal Dead,170\nCrew,10\nPassengers,160\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Novoselivka - Donetsk Obl. - Ukraine\nCountry,Ukraine\nPhase,ENR\nDate,2006-08-22\nLatitude,49.0702778\nLongitude,37.6913889\nCircumstances,Bad Visibility by Night\n\nIncident Union de Transportes Aériens Flight 772 involving a McDonnell Douglas DC-10-30 in 1989\nCasualties,Extremely High\nTotal Dead,170\nCrew,14\nPassengers,156\nGround,0\nNotes,No survivors\nType,INB\nReason,Attack\nLocation,Tenere - Niger\nCountry,Niger\nPhase,ENR\nDate,1989-19-09\nLatitude,18.9546137\nLongitude,10.9134609\nCircumstances,Bad Visibility by Night\n\nIncident Kenya Airways Flight 431 involving a Airbus A310-304 in 2000\nCasualties,Extremely High\nTotal Dead,169\nCrew,10\nPassengers,159\nGround,0\nNotes,Some survivors\nType,COM\nReason,Accident\nLocation,Gulf of Guinea -  Cote d'Ivoire\nCountry,Cote d'Ivoire\nPhase,ENR\nDate,2000-01-30\nLatitude,3.7355442\nLongitude,3.743509\nCircumstances,Bad Visibility by Night\n\nIncident Caspian Airlines Flight 7908 involving a Tupolev Tu-154M in 2009\nCasualties,Extremely High\nTotal Dead,168\nCrew,12\nPassengers,156\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Qazvin - Iran\nCountry,Iran\nPhase,ENR\nDate,2009-07-15\nLatitude,36.266819\nLongitude,50.003811\nCircumstances,Bad Visibility by Night\n\nIncident Pakistan International Airlines Flight 268 involving a Airbus A300B4-200 in 1992\nCasualties,Extremely High\nTotal Dead,167\nCrew,12\nPassengers,155\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Kathmandu - Nepal\nCountry,Nepal\nPhase,APR\nDate,1992-09-28\nLatitude,27.7\nLongitude,85.3333333\nCircumstances,Bad Visibility by Night\n\nIncident Mexicana Flight 940 involving a Boeing 727-264 in 1986\nCasualties,Extremely High\nTotal Dead,167\nCrew,8\nPassengers,159\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Sierra Madre Oriental Mountains - Mexico\nCountry,Mexico\nPhase,ENR\nDate,1986-03-31\nLatitude,-100.4233685\nLongitude,-100.4233685\nCircumstances,Bad Visibility by Night\n\nIncident Aeroflot Flight 4227 involving a Tupolev Tu-154B-2 in 1980\nCasualties,Extremely High\nTotal Dead,166\nCrew,10\nPassengers,156\nGround,0\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Almaty - Kazakhstan\nCountry,Kazakhstan\nPhase,ENR\nDate,1890-07-08\nLatitude,43.255058\nLongitude,76.912628\nCircumstances,Bad Visibility by Night\n\nIncident Dana Air Flight 992 involving a McDonnell Douglas MD-83 in 2012\nCasualties,Extremely High\nTotal Dead,163\nCrew,6\nPassengers,147\nGround,10\nNotes,No survivors\nType,COM\nReason,Accident\nLocation,Lagos - Nigeria\nCountry,Nigeria\nPhase,APR\nDate,2012-06-03\nLatitude,6.441158\nLongitude,3.417977\nCircumstances,Bad Visibility by Night\n\nIncident All Nippon Airways Flight 58 and involving a Boeing 727-281 and\xa0F-86 Sabre in 1971\nCasualties,Extremely High\nTotal Dead,162\nCrew,7\nPassengers,155\nGround,0\nNotes,One survivor\nType,COM\nReason,Accident\nLocation,Shizukuishi - Japan\nCountry,Japan\nPhase,ENR\nDate,1971-07-30\nLatitude,39.6962875\nLongitude,140.9757756\nCircumstances,Bad Visibility by Night\n\nIncident West Caribbean Airways Flight 708 involving a McDonnell Douglas MD-82 in 2005\nCasualties,Extr

Let's have a closer look with by printing each line:

In [6]:
print(text)

Incident American Airlines Flight 11 involving a Boeing 767-223ER in 2001
Casualties,Extremely High
Total Dead,1692
Crew,11
Passengers,81
Ground,1600
Notes,No survivors
Type,INH
Reason,Attack
Location,New York - New York - US
Country,US
Phase,ENR
Date,2001-09-11
Latitude,40.7143528
Longitude,-74.0059731
Circumstances,Good Visibility by Day

Incident United Airlines Flight 175 involving a Boeing 767-222 in 2001
Casualties,Extremely High
Total Dead,965
Crew,9
Passengers,56
Ground,900
Notes,No survivors
Type,INH
Reason,Attack
Location,New York - New York - US
Country,USA
Phase,ENR
Date,2001-09-11
Latitude,40.7143528
Longitude,-74.0059731
Circumstances,Good Visibility by Day

Incident Pan Am Flight 1736 and KLM Flight 4805 involving a Boeing 747-121 and Boeing 747-206B in 1977
Casualties,Extremely High
Total Dead,583
Crew,23
Passengers,560
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Tenerife - Spain
Country,Spain
Phase,TOF
Date,1977-03-27
Latitude,28.2915637
Longitude,-16.6291304
Circumstances,Bad Visibility by Day

Incident Japan Airlines Flight 123 involving a Beoing 747SR-46 in 1985
Casualties,Extremely High
Total Dead,520
Crew,15
Passengers,505
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Ueno - Japan
Country,Japan
Phase,ENR
Date,1985-08-12
Latitude,35.7089461
Longitude,139.7742683
Circumstances,Bad Visibility by Night

Incident Saudi Arabian Flight 763 and involving a Boeing 747-168B and Ilyushin Il-76TD in 1996
Casualties,Extremely High
Total Dead,349
Crew,33
Passengers,316
Ground,0
Notes,No survivors
Type,
Reason,Accident
Location,Charkhi Dadri - India
Country,India
Phase,ENR
Date,1996-11-12
Latitude,28.6
Longitude,76.2667
Circumstances,Bad Visibility by Night

Incident Turkish Airlines Flight 981 involving a McDonnell Douglas DC-10-10 in 1974
Casualties,Extremely High
Total Dead,346
Crew,11
Passengers,335
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Fontaine-Chaalis - France
Country,France
Phase,ENR
Date,1974-03-03
Latitude,49.171795
Longitude,2.684157
Circumstances,Bad Visibility by Night

Incident Air India Flight 182 involving a Boeing 747-237B in 1985
Casualties,Extremely High
Total Dead,329
Crew,22
Passengers,307
Ground,0
Notes,No survivors
Type,INB
Reason,Attack
Location,Atlantic Ocean - Cork - Ireland
Country,Ireland
Phase,ENR
Date,1985-06-23
Latitude,51.8968917
Longitude,-8.4863157
Circumstances,Bad Visibility by Night

Incident Saudia Flight 163 involving a Lockheed L-1011-200 TriStar in 1980
Casualties,Extremely High
Total Dead,301
Crew,14
Passengers,287
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Riyadh - Saudi Arabia
Country,Saudi Arabia
Phase,ENR
Date,1980-08-19
Latitude,24.7116667
Longitude,46.7241667
Circumstances,Bad Visibility by Night

Incident Iran Air Flight 655 involving a Airbus A300B2-203 in 1988
Casualties,Extremely High
Total Dead,290
Crew,16
Passengers,274
Ground,0
Notes,No survivors
Type,EXG
Reason,Attack
Location,Strait of Hormuz - Iran
Country,Iran
Phase,ENR
Date,1988-07-03
Latitude,26.5944754
Longitude,56.4719928
Circumstances,Bad Visibility by Night

Incident Iranian Air Force (15-2280) involving a Ilyushin Il-76MD in 2003
Casualties,Extremely High
Total Dead,275
Crew,18
Passengers,257
Ground,0
Notes,No survivors
Type,MIL
Reason,Accident
Location,Kerman - Iran
Country,Iran
Phase,ENR
Date,2003-02-19
Latitude,30.28027
Longitude,57.06702
Circumstances,Bad Visibility by Night

Incident American Airlines Flight 191 involving a McDonnell Douglas DC-10-10 in 1979
Casualties,Extremely High
Total Dead,273
Crew,13
Passengers,258
Ground,2
Notes,No survivors
Type,COM
Reason,Accident
Location,Des Plaines - Illinois - US
Country,US
Phase,TOF
Date,1979-05-25
Latitude,42.0333623
Longitude,-87.8833991
Circumstances,Bad Visibility by Night

Incident Pan Am Flight 103 involving a Boeing 747-121 in 1988
Casualties,Extremely High
Total Dead,270
Crew,16
Passengers,243
Ground,11
Notes,No survivors
Type,INB
Reason,Attack
Location,Lockerbie - Scotland - UK
Country,UK
Phase,ENR
Date,1988-12-21
Latitude,55.122245
Longitude,-3.349008
Circumstances,Bad Visibility by Night

Incident Korean Air Lines Flight 007 involving a Boeing 747-230B in 1983
Casualties,Extremely High
Total Dead,269
Crew,23
Passengers,246
Ground,0
Notes,No survivors
Type,EXS
Reason,Attack
Location,Sea of Japan - Moneron Island - Russia
Country,Russia
Phase,ENR
Date,1983-09-01
Latitude,46.25
Longitude,141.2333333
Circumstances,Bad Visibility by Night

Incident American Airlines Flight 587 involving a Airbus A300B4-605R in 2001
Casualties,Extremely High
Total Dead,265
Crew,9
Passengers,251
Ground,5
Notes,No survivors
Type,COM
Reason,Accident
Location,Belle Harbor - New York - US
Country,US
Phase,ENR
Date,2001-11-12
Latitude,40.5759385
Longitude,-73.8481906
Circumstances,Bad Visibility by Night

Incident China Airlines Flight 140 involving a Airbus A300B4-622R in 1994
Casualties,Extremely High
Total Dead,264
Crew,15
Passengers,249
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Komaki - Japan
Country,Japan
Phase,APR
Date,1994-04-26
Latitude,35.2903104
Longitude,136.9109515
Circumstances,Bad Visibility by Night

Incident Nigeria Airways Flight 2120 involving a Douglas DC-8-61 in 1991
Casualties,Extremely High
Total Dead,261
Crew,14
Passengers,247
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Jeddah - Saudi Arabia
Country,Saudi Arabia
Phase,APR
Date,1991-07-11
Latitude,21.5433333
Longitude,39.1727778
Circumstances,Bad Visibility by Night

Incident Air New Zealand Flight 901 involving a McDonnell Douglas DC-10-30 in 1979
Casualties,Extremely High
Total Dead,257
Crew,20
Passengers,237
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Mt. Erebus - Antarctica
Country,Antarctica
Phase,ENR
Date,1979-11-28
Latitude,-77.5310559
Longitude,167.0757008
Circumstances,Bad Visibility by Night

Incident Arrow Air Flight 1285 involving a Douglas DC-8-63CF in 1985
Casualties,Extremely High
Total Dead,256
Crew,8
Passengers,248
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Gander - NL. - Canada
Country,Canada
Phase,ICL
Date,1985-12-12
Latitude,48.954408
Longitude,-54.6103488
Circumstances,Bad Visibility by Night

Incident African Air (RA-26222) involving a Antonov An-32B in 1996
Casualties,Extremely High
Total Dead,37
Crew,0
Passengers,0
Ground,237
Notes,Some survivors
Type,COM
Reason,Accident
Location,Kinshasa - DR Congo
Country,DR Congo
Phase,ICL
Date,1996-01-08
Latitude,-4.3316667
Longitude,15.3138889
Circumstances,Bad Visibility by Night

Incident Garuda Indonesia Flight 152 involving a Airbus A300B4-220 in 1997
Casualties,Extremely High
Total Dead,234
Crew,12
Passengers,222
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Medan - Indonesia
Country,Indonesia
Phase,APR
Date,1997-09-26
Latitude,3.585242
Longitude,98.6755979
Circumstances,Bad Visibility by Night

Incident TWA Flight 800 involving a Boeing 747-131 in 1996
Casualties,Extremely High
Total Dead,230
Crew,18
Passengers,212
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Atlantic Ocean - East Moriches - New York - US
Country,US
Phase,ENR
Date,1996-07-17
Latitude,40.8050989
Longitude,-72.7609336
Circumstances,Bad Visibility by Night

Incident Swissair Flight 111 involving a McDonnell Douglas MD-11 in 1998
Casualties,Extremely High
Total Dead,229
Crew,14
Passengers,215
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Atlantic Ocean - Peggys Cove - N.S. - Canada
Country,Canada
Phase,ENR
Date,1998-09-02
Latitude,44.4927778
Longitude,-63.9175
Circumstances,Bad Visibility by Day

Incident Air France Flight 447 involving a Airbus A330-203 in 2009
Casualties,Extremely High
Total Dead,228
Crew,12
Passengers,216
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Atlantic Ocean - Sao Pedro
Country,Sao Pedro
Phase,ENR
Date,2009-06-01
Latitude,03.065833
Longitude,-30.561667
Circumstances,Bad Visibility by Night

Incident Korean Air Flight 801 involving a Boeing 747-3B5 in 1997
Casualties,Extremely High
Total Dead,228
Crew,22
Passengers,206
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Asan - Guam - US
Country,US
Phase,APR
Date,1997-08-06
Latitude,13.4666808
Longitude,144.7454685
Circumstances,Bad Visibility by Night

Incident China Airlines Flight 611 involving a Boeing 747-209B in 2002
Casualties,Extremely High
Total Dead,225
Crew,19
Passengers,206
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Taiwan Strait - Penghu Islands - China
Country,China
Phase,ENR
Date,2002-05-25
Latitude,23.5025
Longitude,119.5052778
Circumstances,Bad Visibility by Night

Incident Lauda Air Flight 004 involving a Boeing 767-3Z9ER in 1991
Casualties,Extremely High
Total Dead,223
Crew,10
Passengers,213
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Phu Toei National Park - Thailand
Country,Thailand
Phase,ENR
Date,1991-05-26
Latitude,14.9413999
Longitude,99.4490951
Circumstances,Bad Visibility by Night

Incident EgyptAir Flight 990 involving a Boeing 767-366ER in 1999
Casualties,Extremely High
Total Dead,217
Crew,15
Passengers,202
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Atlantic Ocean - Nantucket - Massachusetts - US
Country,US
Phase,ENR
Date,1999-10-31
Latitude,41.2834704
Longitude,-70.099451
Circumstances,Bad Visibility by Night

Incident Air India Flight 855 involving a Boeing 747-237B in 1978
Casualties,Extremely High
Total Dead,213
Crew,23
Passengers,190
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Arabian Sea -  Mumbai - India
Country,India
Phase,ENR
Date,1978-01-01
Latitude,19.0759837
Longitude,72.8776559
Circumstances,Bad Visibility by Night

Incident China Airlines Flight 676 involving a Airbus A300-622R in 1998
Casualties,Extremely High
Total Dead,202
Crew,14
Passengers,182
Ground,7
Notes,No survivors
Type,COM
Reason,Accident
Location,Dayuan - Taiwan - China
Country,China
Phase,APR
Date,1998-02-16
Latitude,25.0492632
Longitude,121.193945
Circumstances,Bad Visibility by Night

Incident Aeroflot Flight 7425 involving a Tupolev Tu-154B-2 in 1985
Casualties,Extremely High
Total Dead,0
Crew,9
Passengers,191
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Uchkuduk - Uzbekistan
Country,Uzbekistan
Phase,ENR
Date,1985-07-10
Latitude,42.1566667
Longitude,63.5555556
Circumstances,Bad Visibility by Night

Incident TAM Airlines Flight 3054 involving a Airbus A320-233 in 2007
Casualties,Extremely High
Total Dead,199
Crew,6
Passengers,181
Ground,12
Notes,No survivors
Type,COM
Reason,Accident
Location,Sao Paulo - Brazil
Country,Brazil
Phase,LDG
Date,2007-07-17
Latitude,-23.5489433
Longitude,-46.6388182
Circumstances,Bad Visibility by Night

Incident Martinair Holland Flight 138 involving a Douglas DC-8-55F in 1974
Casualties,Extremely High
Total Dead,191
Crew,9
Passengers,182
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Maskeliya - Sri Lanka
Country,Sri Lanka
Phase,ENR
Date,1974-12-04
Latitude,6.8329294
Longitude,80.5709256
Circumstances,Bad Visibility by Night

Incident American Airlines Flight 77 involving a Boeing 757-223 in 2001
Casualties,Extremely High
Total Dead,189
Crew,6
Passengers,64
Ground,125
Notes,No survivors
Type,INH
Reason,Attack
Location,Arlington - Virginia - US
Country,US
Phase,ENR
Date,2001-09-11
Latitude,38.8799697
Longitude,-77.1067698
Circumstances,Bad Visibility by Day

Incident Alas Nacionales Flight 301 involving a Boeing 757-225 in 1996
Casualties,Extremely High
Total Dead,189
Crew,13
Passengers,176
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Atlantic Ocean - Puerto Plata - Dominican Republic
Country,Dominican Republic
Phase,ENR
Date,1996-02-06
Latitude,19.7807686
Longitude,-70.6871091
Circumstances,Bad Visibility by Night

Incident Alia Royal Jordanian (JY-AEE) involving a Boeing 707-321C in 1975
Casualties,Extremely High
Total Dead,188
Crew,7
Passengers,181
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Tamri - Morocco
Country,Morocco
Phase,ENR
Date,1975-08-03
Latitude,30.6981676
Longitude,-9.8208632
Circumstances,Bad Visibility by Night

Incident LOT Flight 5055 involving a Ilyushin Il-62M in 1987
Casualties,Extremely High
Total Dead,183
Crew,11
Passengers,172
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Warsaw - Poland
Country,Poland
Phase,ENR
Date,1987-05-09
Latitude,52.2296756
Longitude,21.0122287
Circumstances,Bad Visibility by Night

Incident Icelandic Airlines Flight LL 001 involving a Douglas DC-8 in 1978
Casualties,Extremely High
Total Dead,183
Crew,8
Passengers,175
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Katunayake - Sri Lanka
Country,Sri Lanka
Phase,APR
Date,1978-11-15
Latitude,7.1696231
Longitude,79.8912813
Circumstances,Bad Visibility by Night

Incident Avianca Flight 011 involving a Boeing 747-283B in 1983
Casualties,Extremely High
Total Dead,181
Crew,
Passengers,162
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Madrid - Spain
Country,Spain
Phase,APR
Date,1983-11-27
Latitude,40.4167754
Longitude,-3.7037902
Circumstances,Bad Visibility by Night

Incident Inex-Adria Aviopromet Flight 1308 involving a McDonnell Douglas MD-81 in 1981
Casualties,Extremely High
Total Dead,180
Crew,7
Passengers,173
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Mt. San Pietro - Petreto-Bicchisano - Corsica - France
Country,France
Phase,ENR
Date,1981-12-01
Latitude,41.7588889
Longitude,8.9916667
Circumstances,Bad Visibility by Night

Incident Aeroflot Flight 3352 involving a Tupolev Tu-154 in 1984
Casualties,Extremely High
Total Dead,178
Crew,5
Passengers,169
Ground,4
Notes,Some survivors
Type,COM
Reason,Accident
Location,Omsk - Russia
Country,Russia
Phase,LDG
Date,1984-10-11
Latitude,54.9666667
Longitude,73.3833333
Circumstances,Bad Visibility by Night

Incident Aeroflot/Moldovia (CCCP-65816) involving a Tupolev Tu-134A(both) in 1979
Casualties,Extremely High
Total Dead,178
Crew,13
Passengers,165
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Saykyn - Kazakhstan
Country,Kazakhstan
Phase,ENR
Date,1979-08-11
Latitude,48.8125
Longitude,46.7636111
Circumstances,Bad Visibility by Night

Incident British Airways Flight 476 and involving a Hawker Siddeley Trident 3B and in 1976
Casualties,Extremely High
Total Dead,177
Crew,14
Passengers,162
Ground,1
Notes,No survivors
Type,COM
Reason,Accident
Location,Vrbovec - Croatia
Country,Croatia
Phase,ENR
Date,1976-09-10
Latitude,45.8839523
Longitude,16.416766
Circumstances,Bad Visibility by Night

Incident Surinam Airways Flight 764 involving a Douglas DC-8-62 in 1989
Casualties,Extremely High
Total Dead,176
Crew,9
Passengers,167
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Paramaribo - Surinam
Country,Surinam
Phase,APR
Date,1989-06-07
Latitude,5.823201
Longitude,-55.16788
Circumstances,Bad Visibility by Day

Incident Nigeria Airways (JY-ADO) involving a Boeing 707-3D3C in 1973
Casualties,Extremely High
Total Dead,176
Crew,6
Passengers,170
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Kano - Nigeria
Country,Nigeria
Phase,LDG
Date,1973-01-22
Latitude,12
Longitude,8.516667
Circumstances,Bad Visibility by Day

Incident Aeroflot Flight 217 involving a Ilyushin Il-62 in 1972
Casualties,Extremely High
Total Dead,174
Crew,10
Passengers,164
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Moscow - Russia
Country,Russia
Phase,APR
Date,1972-10-13
Latitude,55.755826
Longitude,37.6173
Circumstances,Bad Visibility by Day

Incident Cubana de Aviación Flight 9646 involving a Ilyushin II-62M in 1989
Casualties,Extremely High
Total Dead,171
Crew,11
Passengers,115
Ground,45
Notes,No survivors
Type,COM
Reason,Accident
Location,Havana - Cuba
Country,Cuba
Phase,ICL
Date,1989-09-03
Latitude,23.1168
Longitude,-82.388557
Circumstances,Bad Visibility by Day

Incident Pulkovo Flight 612 involving a Tupolev Tu-154M in 2006
Casualties,Extremely High
Total Dead,170
Crew,10
Passengers,160
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Novoselivka - Donetsk Obl. - Ukraine
Country,Ukraine
Phase,ENR
Date,2006-08-22
Latitude,49.0702778
Longitude,37.6913889
Circumstances,Bad Visibility by Night

Incident Union de Transportes Aériens Flight 772 involving a McDonnell Douglas DC-10-30 in 1989
Casualties,Extremely High
Total Dead,170
Crew,14
Passengers,156
Ground,0
Notes,No survivors
Type,INB
Reason,Attack
Location,Tenere - Niger
Country,Niger
Phase,ENR
Date,1989-19-09
Latitude,18.9546137
Longitude,10.9134609
Circumstances,Bad Visibility by Night

Incident Kenya Airways Flight 431 involving a Airbus A310-304 in 2000
Casualties,Extremely High
Total Dead,169
Crew,10
Passengers,159
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Gulf of Guinea -  Cote d'Ivoire
Country,Cote d'Ivoire
Phase,ENR
Date,2000-01-30
Latitude,3.7355442
Longitude,3.743509
Circumstances,Bad Visibility by Night

Incident Caspian Airlines Flight 7908 involving a Tupolev Tu-154M in 2009
Casualties,Extremely High
Total Dead,168
Crew,12
Passengers,156
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Qazvin - Iran
Country,Iran
Phase,ENR
Date,2009-07-15
Latitude,36.266819
Longitude,50.003811
Circumstances,Bad Visibility by Night

Incident Pakistan International Airlines Flight 268 involving a Airbus A300B4-200 in 1992
Casualties,Extremely High
Total Dead,167
Crew,12
Passengers,155
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Kathmandu - Nepal
Country,Nepal
Phase,APR
Date,1992-09-28
Latitude,27.7
Longitude,85.3333333
Circumstances,Bad Visibility by Night

Incident Mexicana Flight 940 involving a Boeing 727-264 in 1986
Casualties,Extremely High
Total Dead,167
Crew,8
Passengers,159
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Sierra Madre Oriental Mountains - Mexico
Country,Mexico
Phase,ENR
Date,1986-03-31
Latitude,-100.4233685
Longitude,-100.4233685
Circumstances,Bad Visibility by Night

Incident Aeroflot Flight 4227 involving a Tupolev Tu-154B-2 in 1980
Casualties,Extremely High
Total Dead,166
Crew,10
Passengers,156
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Almaty - Kazakhstan
Country,Kazakhstan
Phase,ENR
Date,1890-07-08
Latitude,43.255058
Longitude,76.912628
Circumstances,Bad Visibility by Night

Incident Dana Air Flight 992 involving a McDonnell Douglas MD-83 in 2012
Casualties,Extremely High
Total Dead,163
Crew,6
Passengers,147
Ground,10
Notes,No survivors
Type,COM
Reason,Accident
Location,Lagos - Nigeria
Country,Nigeria
Phase,APR
Date,2012-06-03
Latitude,6.441158
Longitude,3.417977
Circumstances,Bad Visibility by Night

Incident All Nippon Airways Flight 58 and involving a Boeing 727-281 and F-86 Sabre in 1971
Casualties,Extremely High
Total Dead,162
Crew,7
Passengers,155
Ground,0
Notes,One survivor
Type,COM
Reason,Accident
Location,Shizukuishi - Japan
Country,Japan
Phase,ENR
Date,1971-07-30
Latitude,39.6962875
Longitude,140.9757756
Circumstances,Bad Visibility by Night

Incident West Caribbean Airways Flight 708 involving a McDonnell Douglas MD-82 in 2005
Casualties,Extremely High
Total Dead,160
Crew,8
Passengers,152
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Machiques - Venezuela
Country,Venezuela
Phase,ENR
Date,2005-08-16
Latitude,10.06592
Longitude,-72.551872
Circumstances,Bad Visibility by Night

Incident China Northwest Airlines Flight 2303 involving a Tupolev Tu-154M in 1994
Casualties,Extremely High
Total Dead,150
Crew,14
Passengers,146
Ground,0
Notes,No survivors
Type,COM
Reason,Accident
Location,Xian - China
Country,China
Phase,ENR
Date,1984-06-06
Latitude,34.341568
Longitude,108.940175
Circumstances,Bad Visibility by Night

Incident American Airlines Flight 965 involving a Boeing Tu-154M in 1995
Casualties,Extremely High
Total Dead,159
Crew,8
Passengers,151
Ground,0
Notes,Some survivors
Type,COM
Reason,Accident
Location,Buga - Colombia
Country,Colombia
Phase,APR
Date,1995-12-20
Latitude,3.9
Longitude,-76.3
Circumstances,Bad Visibility by Night

What do we learn?

1. Data for one observation stored in 16 rows.
2. A blank line at the start and blank lines at the end of each observation.
3. The data seems to be comma delimited, however with missing commas after 'Incident' in the leading row for observations.


## Step 2 Tidy up the raw data file

We will make changes to the raw data file and save it to a file (readable via pandas) by read each line and:

1. add comma after "Incident",
2. remove blank lines, and
2. save the file to 'AirCrashes_fixed.csv'

In [7]:
with open('/content/drive/Shareddrives/FIT5196_S2_2026/Week2/AirCrashes_raw.csv','r') as infile:
    with open('/content/drive/MyDrive/AirCrashes_fixed.csv','a') as outfile: # somewhere to write output to.
        text = infile.read()
        text = text.split('\n') # create a list to iterate over
        for line in text:
            if line == '': continue # deal with the blank lines
            if line.startswith('Incident'):
                line = line.replace('Incident','Incident,') # add the comma after 'Incident' column header
            print(line + '\n\r',file=outfile) #create a new csv with newline and carrige return characters

We will have a quick check:

In [9]:
# Use /content/drive/MyDrive/AirCrashes_fixed.csv if you use Colab, the following code only works for local file review
!cat AirCrashes_fixed.csv

Incident, American Airlines Flight 11 involving a Boeing 767-223ER in 2001

Casualties,Extremely High

Total Dead,1692

Crew,11

Passengers,81

Ground,1600

Notes,No survivors

Type,INH

Reason,Attack

Location,New York - New York - US

Country,US

Phase,ENR

Date,2001-09-11

Latitude,40.7143528

Longitude,-74.0059731

Circumstances,Good Visibility by Day

Incident, United Airlines Flight 175 involving a Boeing 767-222 in 2001

Casualties,Extremely High

Total Dead,965

Crew,9

Passengers,56

Ground,900

Notes,No survivors

Type,INH

Reason,Attack

Location,New York - New York - US

Country,USA

Phase,ENR

Date,2001-09-11

Latitude,40.7143528

Longitude,-74.0059731

Circumstances,Good Visibility by Day

Incident, Pan Am Flight 1736 and KLM Flight 4805 involving a Boeing 747-121 and Boeing 747-206B in 1977

Casualties,Extremely High

Total Dead,583

Crew,23

Passengers,560

Ground,0

Notes,Some survivors

Type,COM

Reason,Accident

Location,Tenerife - Spain

Country,Spain

Phase,TOF

Date,1977-03-27

Latitude,28.2915637

Longitude,-16.6291304

Circumstances,Bad Visibility by Day

Incident, Japan Airlines Flight 123 involving a Beoing 747SR-46 in 1985

Casualties,Extremely High

Total Dead,520

Crew,15

Passengers,505

Ground,0

Notes,Some survivors

Type,COM

Reason,Accident

Location,Ueno - Japan

Country,Japan

Phase,ENR

Date,1985-08-12

Latitude,35.7089461

Longitude,139.7742683

Circumstances,Bad Visibility by Night

Incident, Saudi Arabian Flight 763 and involving a Boeing 747-168B and Ilyushin Il-76TD in 1996

Casualties,Extremely High

Total Dead,349

Crew,33

Passengers,316

Ground,0

Notes,No survivors

Type,

Reason,Accident

Location,Charkhi Dadri - India

Country,India

Phase,ENR

Date,1996-11-12

Latitude,28.6

Longitude,76.2667

Circumstances,Bad Visibility by Night

Incident, Turkish Airlines Flight 981 involving a McDonnell Douglas DC-10-10 in 1974

Casualties,Extremely High

Total Dead,346

Crew,11

Passengers,335

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Fontaine-Chaalis - France

Country,France

Phase,ENR

Date,1974-03-03

Latitude,49.171795

Longitude,2.684157

Circumstances,Bad Visibility by Night

Incident, Air India Flight 182 involving a Boeing 747-237B in 1985

Casualties,Extremely High

Total Dead,329

Crew,22

Passengers,307

Ground,0

Notes,No survivors

Type,INB

Reason,Attack

Location,Atlantic Ocean - Cork - Ireland

Country,Ireland

Phase,ENR

Date,1985-06-23

Latitude,51.8968917

Longitude,-8.4863157

Circumstances,Bad Visibility by Night

Incident, Saudia Flight 163 involving a Lockheed L-1011-200 TriStar in 1980

Casualties,Extremely High

Total Dead,301

Crew,14

Passengers,287

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Riyadh - Saudi Arabia

Country,Saudi Arabia

Phase,ENR

Date,1980-08-19

Latitude,24.7116667

Longitude,46.7241667

Circumstances,Bad Visibility by Night

Incident, Iran Air Flight 655 involving a Airbus A300B2-203 in 1988

Casualties,Extremely High

Total Dead,290

Crew,16

Passengers,274

Ground,0

Notes,No survivors

Type,EXG

Reason,Attack

Location,Strait of Hormuz - Iran

Country,Iran

Phase,ENR

Date,1988-07-03

Latitude,26.5944754

Longitude,56.4719928

Circumstances,Bad Visibility by Night

Incident, Iranian Air Force (15-2280) involving a Ilyushin Il-76MD in 2003

Casualties,Extremely High

Total Dead,275

Crew,18

Passengers,257

Ground,0

Notes,No survivors

Type,MIL

Reason,Accident

Location,Kerman - Iran

Country,Iran

Phase,ENR

Date,2003-02-19

Latitude,30.28027

Longitude,57.06702

Circumstances,Bad Visibility by Night

Incident, American Airlines Flight 191 involving a McDonnell Douglas DC-10-10 in 1979

Casualties,Extremely High

Total Dead,273

Crew,13

Passengers,258

Ground,2

Notes,No survivors

Type,COM

Reason,Accident

Location,Des Plaines - Illinois - US

Country,US

Phase,TOF

Date,1979-05-25

Latitude,42.0333623

Longitude,-87.8833991

Circumstances,Bad Visibility by Night

Incident, Pan Am Flight 103 involving a Boeing 747-121 in 1988

Casualties,Extremely High

Total Dead,270

Crew,16

Passengers,243

Ground,11

Notes,No survivors

Type,INB

Reason,Attack

Location,Lockerbie - Scotland - UK

Country,UK

Phase,ENR

Date,1988-12-21

Latitude,55.122245

Longitude,-3.349008

Circumstances,Bad Visibility by Night

Incident, Korean Air Lines Flight 007 involving a Boeing 747-230B in 1983

Casualties,Extremely High

Total Dead,269

Crew,23

Passengers,246

Ground,0

Notes,No survivors

Type,EXS

Reason,Attack

Location,Sea of Japan - Moneron Island - Russia

Country,Russia

Phase,ENR

Date,1983-09-01

Latitude,46.25

Longitude,141.2333333

Circumstances,Bad Visibility by Night

Incident, American Airlines Flight 587 involving a Airbus A300B4-605R in 2001

Casualties,Extremely High

Total Dead,265

Crew,9

Passengers,251

Ground,5

Notes,No survivors

Type,COM

Reason,Accident

Location,Belle Harbor - New York - US

Country,US

Phase,ENR

Date,2001-11-12

Latitude,40.5759385

Longitude,-73.8481906

Circumstances,Bad Visibility by Night

Incident, China Airlines Flight 140 involving a Airbus A300B4-622R in 1994

Casualties,Extremely High

Total Dead,264

Crew,15

Passengers,249

Ground,0

Notes,Some survivors

Type,COM

Reason,Accident

Location,Komaki - Japan

Country,Japan

Phase,APR

Date,1994-04-26

Latitude,35.2903104

Longitude,136.9109515

Circumstances,Bad Visibility by Night

Incident, Nigeria Airways Flight 2120 involving a Douglas DC-8-61 in 1991

Casualties,Extremely High

Total Dead,261

Crew,14

Passengers,247

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Jeddah - Saudi Arabia

Country,Saudi Arabia

Phase,APR

Date,1991-07-11

Latitude,21.5433333

Longitude,39.1727778

Circumstances,Bad Visibility by Night

Incident, Air New Zealand Flight 901 involving a McDonnell Douglas DC-10-30 in 1979

Casualties,Extremely High

Total Dead,257

Crew,20

Passengers,237

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Mt. Erebus - Antarctica

Country,Antarctica

Phase,ENR

Date,1979-11-28

Latitude,-77.5310559

Longitude,167.0757008

Circumstances,Bad Visibility by Night

Incident, Arrow Air Flight 1285 involving a Douglas DC-8-63CF in 1985

Casualties,Extremely High

Total Dead,256

Crew,8

Passengers,248

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Gander - NL. - Canada

Country,Canada

Phase,ICL

Date,1985-12-12

Latitude,48.954408

Longitude,-54.6103488

Circumstances,Bad Visibility by Night

Incident, African Air (RA-26222) involving a Antonov An-32B in 1996

Casualties,Extremely High

Total Dead,37

Crew,0

Passengers,0

Ground,237

Notes,Some survivors

Type,COM

Reason,Accident

Location,Kinshasa - DR Congo

Country,DR Congo

Phase,ICL

Date,1996-01-08

Latitude,-4.3316667

Longitude,15.3138889

Circumstances,Bad Visibility by Night

Incident, Garuda Indonesia Flight 152 involving a Airbus A300B4-220 in 1997

Casualties,Extremely High

Total Dead,234

Crew,12

Passengers,222

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Medan - Indonesia

Country,Indonesia

Phase,APR

Date,1997-09-26

Latitude,3.585242

Longitude,98.6755979

Circumstances,Bad Visibility by Night

Incident, TWA Flight 800 involving a Boeing 747-131 in 1996

Casualties,Extremely High

Total Dead,230

Crew,18

Passengers,212

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Atlantic Ocean - East Moriches - New York - US

Country,US

Phase,ENR

Date,1996-07-17

Latitude,40.8050989

Longitude,-72.7609336

Circumstances,Bad Visibility by Night

Incident, Swissair Flight 111 involving a McDonnell Douglas MD-11 in 1998

Casualties,Extremely High

Total Dead,229

Crew,14

Passengers,215

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Atlantic Ocean - Peggys Cove - N.S. - Canada

Country,Canada

Phase,ENR

Date,1998-09-02

Latitude,44.4927778

Longitude,-63.9175

Circumstances,Bad Visibility by Day

Incident, Air France Flight 447 involving a Airbus A330-203 in 2009

Casualties,Extremely High

Total Dead,228

Crew,12

Passengers,216

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Atlantic Ocean - Sao Pedro

Country,Sao Pedro

Phase,ENR

Date,2009-06-01

Latitude,03.065833

Longitude,-30.561667

Circumstances,Bad Visibility by Night

Incident, Korean Air Flight 801 involving a Boeing 747-3B5 in 1997

Casualties,Extremely High

Total Dead,228

Crew,22

Passengers,206

Ground,0

Notes,Some survivors

Type,COM

Reason,Accident

Location,Asan - Guam - US

Country,US

Phase,APR

Date,1997-08-06

Latitude,13.4666808

Longitude,144.7454685

Circumstances,Bad Visibility by Night

Incident, China Airlines Flight 611 involving a Boeing 747-209B in 2002

Casualties,Extremely High

Total Dead,225

Crew,19

Passengers,206

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Taiwan Strait - Penghu Islands - China

Country,China

Phase,ENR

Date,2002-05-25

Latitude,23.5025

Longitude,119.5052778

Circumstances,Bad Visibility by Night

Incident, Lauda Air Flight 004 involving a Boeing 767-3Z9ER in 1991

Casualties,Extremely High

Total Dead,223

Crew,10

Passengers,213

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Phu Toei National Park - Thailand

Country,Thailand

Phase,ENR

Date,1991-05-26

Latitude,14.9413999

Longitude,99.4490951

Circumstances,Bad Visibility by Night

Incident, EgyptAir Flight 990 involving a Boeing 767-366ER in 1999

Casualties,Extremely High

Total Dead,217

Crew,15

Passengers,202

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Atlantic Ocean - Nantucket - Massachusetts - US

Country,US

Phase,ENR

Date,1999-10-31

Latitude,41.2834704

Longitude,-70.099451

Circumstances,Bad Visibility by Night

Incident, Air India Flight 855 involving a Boeing 747-237B in 1978

Casualties,Extremely High

Total Dead,213

Crew,23

Passengers,190

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Arabian Sea -  Mumbai - India

Country,India

Phase,ENR

Date,1978-01-01

Latitude,19.0759837

Longitude,72.8776559

Circumstances,Bad Visibility by Night

Incident, China Airlines Flight 676 involving a Airbus A300-622R in 1998

Casualties,Extremely High

Total Dead,202

Crew,14

Passengers,182

Ground,7

Notes,No survivors

Type,COM

Reason,Accident

Location,Dayuan - Taiwan - China

Country,China

Phase,APR

Date,1998-02-16

Latitude,25.0492632

Longitude,121.193945

Circumstances,Bad Visibility by Night

Incident, Aeroflot Flight 7425 involving a Tupolev Tu-154B-2 in 1985

Casualties,Extremely High

Total Dead,0

Crew,9

Passengers,191

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Uchkuduk - Uzbekistan

Country,Uzbekistan

Phase,ENR

Date,1985-07-10

Latitude,42.1566667

Longitude,63.5555556

Circumstances,Bad Visibility by Night

Incident, TAM Airlines Flight 3054 involving a Airbus A320-233 in 2007

Casualties,Extremely High

Total Dead,199

Crew,6

Passengers,181

Ground,12

Notes,No survivors

Type,COM

Reason,Accident

Location,Sao Paulo - Brazil

Country,Brazil

Phase,LDG

Date,2007-07-17

Latitude,-23.5489433

Longitude,-46.6388182

Circumstances,Bad Visibility by Night

Incident, Martinair Holland Flight 138 involving a Douglas DC-8-55F in 1974

Casualties,Extremely High

Total Dead,191

Crew,9

Passengers,182

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Maskeliya - Sri Lanka

Country,Sri Lanka

Phase,ENR

Date,1974-12-04

Latitude,6.8329294

Longitude,80.5709256

Circumstances,Bad Visibility by Night

Incident, American Airlines Flight 77 involving a Boeing 757-223 in 2001

Casualties,Extremely High

Total Dead,189

Crew,6

Passengers,64

Ground,125

Notes,No survivors

Type,INH

Reason,Attack

Location,Arlington - Virginia - US

Country,US

Phase,ENR

Date,2001-09-11

Latitude,38.8799697

Longitude,-77.1067698

Circumstances,Bad Visibility by Day

Incident, Alas Nacionales Flight 301 involving a Boeing 757-225 in 1996

Casualties,Extremely High

Total Dead,189

Crew,13

Passengers,176

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Atlantic Ocean - Puerto Plata - Dominican Republic

Country,Dominican Republic

Phase,ENR

Date,1996-02-06

Latitude,19.7807686

Longitude,-70.6871091

Circumstances,Bad Visibility by Night

Incident, Alia Royal Jordanian (JY-AEE) involving a Boeing 707-321C in 1975

Casualties,Extremely High

Total Dead,188

Crew,7

Passengers,181

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Tamri - Morocco

Country,Morocco

Phase,ENR

Date,1975-08-03

Latitude,30.6981676

Longitude,-9.8208632

Circumstances,Bad Visibility by Night

Incident, LOT Flight 5055 involving a Ilyushin Il-62M in 1987

Casualties,Extremely High

Total Dead,183

Crew,11

Passengers,172

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Warsaw - Poland

Country,Poland

Phase,ENR

Date,1987-05-09

Latitude,52.2296756

Longitude,21.0122287

Circumstances,Bad Visibility by Night

Incident, Icelandic Airlines Flight LL 001 involving a Douglas DC-8 in 1978

Casualties,Extremely High

Total Dead,183

Crew,8

Passengers,175

Ground,0

Notes,Some survivors

Type,COM

Reason,Accident

Location,Katunayake - Sri Lanka

Country,Sri Lanka

Phase,APR

Date,1978-11-15

Latitude,7.1696231

Longitude,79.8912813

Circumstances,Bad Visibility by Night

Incident, Avianca Flight 011 involving a Boeing 747-283B in 1983

Casualties,Extremely High

Total Dead,181

Crew,

Passengers,162

Ground,0

Notes,Some survivors

Type,COM

Reason,Accident

Location,Madrid - Spain

Country,Spain

Phase,APR

Date,1983-11-27

Latitude,40.4167754

Longitude,-3.7037902

Circumstances,Bad Visibility by Night

Incident, Inex-Adria Aviopromet Flight 1308 involving a McDonnell Douglas MD-81 in 1981

Casualties,Extremely High

Total Dead,180

Crew,7

Passengers,173

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Mt. San Pietro - Petreto-Bicchisano - Corsica - France

Country,France

Phase,ENR

Date,1981-12-01

Latitude,41.7588889

Longitude,8.9916667

Circumstances,Bad Visibility by Night

Incident, Aeroflot Flight 3352 involving a Tupolev Tu-154 in 1984

Casualties,Extremely High

Total Dead,178

Crew,5

Passengers,169

Ground,4

Notes,Some survivors

Type,COM

Reason,Accident

Location,Omsk - Russia

Country,Russia

Phase,LDG

Date,1984-10-11

Latitude,54.9666667

Longitude,73.3833333

Circumstances,Bad Visibility by Night

Incident, Aeroflot/Moldovia (CCCP-65816) involving a Tupolev Tu-134A(both) in 1979

Casualties,Extremely High

Total Dead,178

Crew,13

Passengers,165

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Saykyn - Kazakhstan

Country,Kazakhstan

Phase,ENR

Date,1979-08-11

Latitude,48.8125

Longitude,46.7636111

Circumstances,Bad Visibility by Night

Incident, British Airways Flight 476 and involving a Hawker Siddeley Trident 3B and in 1976

Casualties,Extremely High

Total Dead,177

Crew,14

Passengers,162

Ground,1

Notes,No survivors

Type,COM

Reason,Accident

Location,Vrbovec - Croatia

Country,Croatia

Phase,ENR

Date,1976-09-10

Latitude,45.8839523

Longitude,16.416766

Circumstances,Bad Visibility by Night

Incident, Surinam Airways Flight 764 involving a Douglas DC-8-62 in 1989

Casualties,Extremely High

Total Dead,176

Crew,9

Passengers,167

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Paramaribo - Surinam

Country,Surinam

Phase,APR

Date,1989-06-07

Latitude,5.823201

Longitude,-55.16788

Circumstances,Bad Visibility by Day

Incident, Nigeria Airways (JY-ADO) involving a Boeing 707-3D3C in 1973

Casualties,Extremely High

Total Dead,176

Crew,6

Passengers,170

Ground,0

Notes,Some survivors

Type,COM

Reason,Accident

Location,Kano - Nigeria

Country,Nigeria

Phase,LDG

Date,1973-01-22

Latitude,12

Longitude,8.516667

Circumstances,Bad Visibility by Day

Incident, Aeroflot Flight 217 involving a Ilyushin Il-62 in 1972

Casualties,Extremely High

Total Dead,174

Crew,10

Passengers,164

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Moscow - Russia

Country,Russia

Phase,APR

Date,1972-10-13

Latitude,55.755826

Longitude,37.6173

Circumstances,Bad Visibility by Day

Incident, Cubana de Aviación Flight 9646 involving a Ilyushin II-62M in 1989

Casualties,Extremely High

Total Dead,171

Crew,11

Passengers,115

Ground,45

Notes,No survivors

Type,COM

Reason,Accident

Location,Havana - Cuba

Country,Cuba

Phase,ICL

Date,1989-09-03

Latitude,23.1168

Longitude,-82.388557

Circumstances,Bad Visibility by Day

Incident, Pulkovo Flight 612 involving a Tupolev Tu-154M in 2006

Casualties,Extremely High

Total Dead,170

Crew,10

Passengers,160

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Novoselivka - Donetsk Obl. - Ukraine

Country,Ukraine

Phase,ENR

Date,2006-08-22

Latitude,49.0702778

Longitude,37.6913889

Circumstances,Bad Visibility by Night

Incident, Union de Transportes Aériens Flight 772 involving a McDonnell Douglas DC-10-30 in 1989

Casualties,Extremely High

Total Dead,170

Crew,14

Passengers,156

Ground,0

Notes,No survivors

Type,INB

Reason,Attack

Location,Tenere - Niger

Country,Niger

Phase,ENR

Date,1989-19-09

Latitude,18.9546137

Longitude,10.9134609

Circumstances,Bad Visibility by Night

Incident, Kenya Airways Flight 431 involving a Airbus A310-304 in 2000

Casualties,Extremely High

Total Dead,169

Crew,10

Passengers,159

Ground,0

Notes,Some survivors

Type,COM

Reason,Accident

Location,Gulf of Guinea -  Cote d'Ivoire

Country,Cote d'Ivoire

Phase,ENR

Date,2000-01-30

Latitude,3.7355442

Longitude,3.743509

Circumstances,Bad Visibility by Night

Incident, Caspian Airlines Flight 7908 involving a Tupolev Tu-154M in 2009

Casualties,Extremely High

Total Dead,168

Crew,12

Passengers,156

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Qazvin - Iran

Country,Iran

Phase,ENR

Date,2009-07-15

Latitude,36.266819

Longitude,50.003811

Circumstances,Bad Visibility by Night

Incident, Pakistan International Airlines Flight 268 involving a Airbus A300B4-200 in 1992

Casualties,Extremely High

Total Dead,167

Crew,12

Passengers,155

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Kathmandu - Nepal

Country,Nepal

Phase,APR

Date,1992-09-28

Latitude,27.7

Longitude,85.3333333

Circumstances,Bad Visibility by Night

Incident, Mexicana Flight 940 involving a Boeing 727-264 in 1986

Casualties,Extremely High

Total Dead,167

Crew,8

Passengers,159

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Sierra Madre Oriental Mountains - Mexico

Country,Mexico

Phase,ENR

Date,1986-03-31

Latitude,-100.4233685

Longitude,-100.4233685

Circumstances,Bad Visibility by Night

Incident, Aeroflot Flight 4227 involving a Tupolev Tu-154B-2 in 1980

Casualties,Extremely High

Total Dead,166

Crew,10

Passengers,156

Ground,0

Notes,No survivors

Type,COM

Reason,Accident

Location,Almaty - Kazakhstan

Country,Kazakhstan

Phase,ENR

Date,1890-07-08

Latitude,43.255058

Longitude,76.912628

Circumstances,Bad Visibility by Night

Incident, Dana Air Flight 992 involving a McDonnell Douglas MD-83 in 2012

Casualties,Extremely High

Total Dead,163

Crew,6

Passengers,147

Ground,10

Notes,No survivors

Type,COM

Reason,Accident

Location,Lagos - Nigeria

Country,Nigeria

Phase,APR

Date,2012-06-03

Latitude,6.441158

Longitude,3.417977

Circumstances,Bad Visibility by Night

Incident, All Nippon Airways Flight 58 and involving a Boeing 727-281 and F-86 Sabre in 1971

Casualties,Extremely High

Total Dead,162

Crew,7

Passengers,155

Ground,0

Notes,One survivor

Type,COM

Reason,Accident

Location,Shizukuishi - Japan

Country,Japan

Phase,ENR

Date,1971-07-30

Latitude,39.6962875

Longitude,140.9757756

Circumstances,Bad Visibility by Night

Incident, West Caribbean Airways Flight 708 involving a McDonnell Douglas MD-82 in 2005

Casualties,Extremely High

Total Dead,160

Crew,8

Passengers,152

Ground,0


That looks better.


## Step 3 Read data to a pandas dataframe

Now we import the dataset to pandas.

In [10]:
pd.read_csv('/content/drive/MyDrive/AirCrashes_fixed.csv').head()

,Incident,American Airlines Flight 11 involving a Boeing 767-223ER in 2001
0,Casualties,Extremely High
1,Total Dead,1692
2,Crew,11
3,Passengers,81
4,Ground,1600

OK, so no header.

In [11]:
data=pd.read_csv('/content/drive/MyDrive/AirCrashes_fixed.csv',header=None).head(20)
data

                0                                                  1
0        Incident   American Airlines Flight 11 involving a Boein...
1      Casualties                                     Extremely High
2      Total Dead                                               1692
3            Crew                                                 11
4      Passengers                                                 81
5          Ground                                               1600
6           Notes                                       No survivors
7            Type                                                INH
8          Reason                                             Attack
9        Location                           New York - New York - US
10        Country                                                 US
11          Phase                                                ENR
12           Date                                         2001-09-11
13       Latitude                                         40.7143528
14      Longitude                                        -74.0059731
15  Circumstances                             Good Visibility by Day
16       Incident   United Airlines Flight 175 involving a Boeing...
17     Casualties                                     Extremely High
18     Total Dead                                                965
19           Crew                                                  9

And the csv is on it's side and repeats every 16 rows. This looks like a job for chunk!

## Step 4 Transpose each observation from long to wide and append all observations

We achieve this by

1. divide the dataset to chunks when using read.csv (chunksize is 16 rows);
2. transpose data from long to wide for each chunk and then
3. append each transposed line to the "Master" dataset

We have tested with only a few observations, which worked. Here are the final code:

In [13]:
# read data in to chunks
chunky_data = pd.read_csv('/content/drive/MyDrive/AirCrashes_fixed.csv',header = None,iterator=True,chunksize=16)

# define an empty dataframe

if sys.version_info[0] == 3:
    master = pd.DataFrame(columns = range(16))
else:
    master = pd.DataFrame(columns = range(16))
# loop through each chunk in chunky_data
for chunk in chunky_data:
    # transponse chunk and save the second row (the row containing values not header) to "row"
    row = chunk.T.iloc[1,:]
    # append a "row" to the master dataframe
    master = pd.concat([master, pd.DataFrame([row.values], columns=master.columns)], ignore_index=True)
# print master
master

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,American Airlines Flight 11 involving a Boein...,Extremely High,1692,11,81,1600,No survivors,INH,Attack,New York - New York - US,US,ENR,2001-09-11,40.7143528,-74.0059731,Good Visibility by Day
1,United Airlines Flight 175 involving a Boeing...,Extremely High,965,9,56,900,No survivors,INH,Attack,New York - New York - US,USA,ENR,2001-09-11,40.7143528,-74.0059731,Good Visibility by Day
2,Pan Am Flight 1736 and KLM Flight 4805 involv...,Extremely High,583,23,560,0,Some survivors,COM,Accident,Tenerife - Spain,Spain,TOF,1977-03-27,28.2915637,-16.6291304,Bad Visibility by Day
3,Japan Airlines Flight 123 involving a Beoing ...,Extremely High,520,15,505,0,Some survivors,COM,Accident,Ueno - Japan,Japan,ENR,1985-08-12,35.7089461,139.7742683,Bad Visibility by Night
4,Saudi Arabian Flight 763 and involving a Boei...,Extremely High,349,33,316,0,No survivors,,Accident,Charkhi Dadri - India,India,ENR,1996-11-12,28.6,76.2667,Bad Visibility by Night
5,Turkish Airlines Flight 981 involving a McDon...,Extremely High,346,11,335,0,No survivors,COM,Accident,Fontaine-Chaalis - France,France,ENR,1974-03-03,49.171795,2.684157,Bad Visibility by Night
6,Air India Flight 182 involving a Boeing 747-2...,Extremely High,329,22,307,0,No survivors,INB,Attack,Atlantic Ocean - Cork - Ireland,Ireland,ENR,1985-06-23,51.8968917,-8.4863157,Bad Visibility by Night
7,Saudia Flight 163 involving a Lockheed L-1011...,Extremely High,301,14,287,0,No survivors,COM,Accident,Riyadh - Saudi Arabia,Saudi Arabia,ENR,1980-08-19,24.7116667,46.7241667,Bad Visibility by Night
8,Iran Air Flight 655 involving a Airbus A300B2...,Extremely High,290,16,274,0,No survivors,EXG,Attack,Strait of Hormuz - Iran,Iran,ENR,1988-07-03,26.5944754,56.4719928,Bad Visibility by Night
9,Iranian Air Force (15-2280) involving a Ilyus...,Extremely High,275,18,257,0,No survivors,MIL,Accident,Kerman - Iran,Iran,ENR,2003-02-19,30.28027,57.06702,Bad Visibility by Night
10,American Airlines Flight 191 involving a McDo...,Extremely High,273,13,258,2,No survivors,COM,Accident,Des Plaines - Illinois - US,US,TOF,1979-05-25,42.0333623,-87.8833991,Bad Visibility by Night
11,Pan Am Flight 103 involving a Boeing 747-121 ...,Extremely High,270,16,243,11,No survivors,INB,Attack,Lockerbie - Scotland - UK,UK,ENR,1988-12-21,55.122245,-3.349008,Bad Visibility by Night
12,Korean Air Lines Flight 007 involving a Boein...,Extremely High,269,23,246,0,No survivors,EXS,Attack,Sea of Japan - Moneron Island - Russia,Russia,ENR,1983-09-01,46.25,141.2333333,Bad Visibility by Night
13,American Airlines Flight 587 involving a Airb...,Extremely High,265,9,251,5,No survivors,COM,Accident,Belle Harbor - New York - US,US,ENR,2001-11-12,40.5759385,-73.8481906,Bad Visibility by Night
14,China Airlines Flight 140 involving a Airbus ...,Extremely High,264,15,249,0,Some survivors,COM,Accident,Komaki - Japan,Japan,APR,1994-04-26,35.2903104,136.9109515,Bad Visibility by Night
15,Nigeria Airways Flight 2120 involving a Dougl...,Extremely High,261,14,247,0,No survivors,COM,Accident,Jeddah - Saudi Arabia,Saudi Arabia,APR,1991-07-11,21.5433333,39.1727778,Bad Visibility by Night
16,Air New Zealand Flight 901 involving a McDonn...,Extremely High,257,20,237,0,No survivors,COM,Accident,Mt. Erebus - Antarctica,Antarctica,ENR,1979-11-28,-77.5310559,167.0757008,Bad Visibility by Night
17,Arrow Air Flight 1285 involving a Douglas DC-...,Extremely High,256,8,248,0,No survivors,COM,Accident,Gander - NL. - Canada,Canada,ICL,1985-12-12,48.954408,-54.6103488,Bad Visibility by Night
18,African Air (RA-26222) involving a Antonov An...,Extremely High,37,0,0,237,Some survivors,COM,Accident,Kinshasa - DR Congo,DR Congo,ICL,1996-01-08,-4.3316667,15.3138889,Bad Visibility by Night
19,Garuda Indonesia Flight 152 involving a Airbu...,Extremely High,234,12,222,0,No survivors,COM,Accident,Medan - Indonesia,Indonesia,APR,1997-09-26,3.585242,98.6755979,Bad Visibility by Night
20,TWA Flight 800 involving a Boeing 747-131 in ...,Extremely High,230,18,212,0,No survivors,COM,Accident,Atlantic Ocean - East Moriches - New York - US,US,ENR,1996-07-17,40.8050989,-72.7609336,Bad Visibility by Night
21,Swissair Flight 111 involving a McDonnell Dou...,Extremely High,229,14,215,0,No survivors,COM,Accident,Atlantic Ocean - Peggys Cove - N.S. - Canada,Canada,ENR,1998-09-02,44.4927778,-63.9175,Bad Visibility by Day
22,Air France Flight 447 involving a Airbus A330...,Extremely High,228,12,216,0,No survivors,COM,Accident,Atlantic Ocean - Sao Pedro,Sao Pedro,ENR,2009-06-01,03.065833,-30.561667,Bad Visibility by Night
23,Korean Air Flight 801 involving a Boeing 747-...,Extremely High,228,22,206,0,Some survivors,COM,Accident,Asan - Guam - US,US,APR,1997-08-06,13.4666808,144.7454685,Bad Visibility by Night
24,China Airlines Flight 611 involving a Boeing ...,Extremely High,225,19,206,0,No survivors,COM,Accident,Taiwan Strait - Penghu Islands - China,China,ENR,2002-05-25,23.5025,119.5052778,Bad Visibility by Night
25,Lauda Air Flight 004 involving a Boeing 767-3...,Extremely High,223,10,213,0,No survivors,COM,Accident,Phu Toei National Park - Thailand,Thailand,ENR,1991-05-26,14.9413999,99.4490951,Bad Visibility by Night
26,EgyptAir Flight 990 involving a Boeing 767-36...,Extremely High,217,15,202,0,No survivors,COM,Accident,Atlantic Ocean - Nantucket - Massachusetts - US,US,ENR,1999-10-31,41.2834704,-70.099451,Bad Visibility by Night
27,Air India Flight 855 involving a Boeing 747-2...,Extremely High,213,23,190,0,No survivors,COM,Accident,Arabian Sea - Mumbai - India,India,ENR,1978-01-01,19.0759837,72.8776559,Bad Visibility by Night
28,China Airlines Flight 676 involving a Airbus ...,Extremely High,202,14,182,7,No survivors,COM,Accident,Dayuan - Taiwan - China,China,APR,1998-02-16,25.0492632,121.193945,Bad Visibility by Night
29,Aeroflot Flight 7425 involving a Tupolev Tu-1...,Extremely High,0,9,191,0,No survivors,COM,Accident,Uchkuduk - Uzbekistan,Uzbekistan,ENR,1985-07-10,42.1566667,63.5555556,Bad Visibility by Night
30,TAM Airlines Flight 3054 involving a Airbus A...,Extremely High,199,6,181,12,No survivors,COM,Accident,Sao Paulo - Brazil,Brazil,LDG,2007-07-17,-23.5489433,-46.6388182,Bad Visibility by Night
31,Martinair Holland Flight 138 involving a Doug...,Extremely High,191,9,182,0,No survivors,COM,Accident,Maskeliya - Sri Lanka,Sri Lanka,ENR,1974-12-04,6.8329294,80.5709256,Bad Visibility by Night
32,American Airlines Flight 77 involving a Boein...,Extremely High,189,6,64,125,No survivors,INH,Attack,Arlington - Virginia - US,US,ENR,2001-09-11,38.8799697,-77.1067698,Bad Visibility by Day
33,Alas Nacionales Flight 301 involving a Boeing...,Extremely High,189,13,176,0,No survivors,COM,Accident,Atlantic Ocean - Puerto Plata - Dominican Repu...,Dominican Republic,ENR,1996-02-06,19.7807686,-70.6871091,Bad Visibility by Night
34,Alia Royal Jordanian (JY-AEE) involving a Boe...,Extremely High,188,7,181,0,No survivors,COM,Accident,Tamri - Morocco,Morocco,ENR,1975-08-03,30.6981676,-9.8208632,Bad Visibility by Night
35,LOT Flight 5055 involving a Ilyushin Il-62M i...,Extremely High,183,11,172,0,No survivors,COM,Accident,Warsaw - Poland,Poland,ENR,1987-05-09,52.2296756,21.0122287,Bad Visibility by Night
36,Icelandic Airlines Flight LL 001 involving a ...,Extremely High,183,8,175,0,Some survivors,COM,Accident,Katunayake - Sri Lanka,Sri Lanka,APR,1978-11-15,7.1696231,79.8912813,Bad Visibility by Night
37,Avianca Flight 011 involving a Boeing 747-283...,Extremely High,181,NaN,162,0,Some survivors,COM,Accident,Madrid - Spain,Spain,APR,1983-11-27,40.4167754,-3.7037902,Bad Visibility by Night
38,Inex-Adria Aviopromet Flight 1308 involving a...,Extremely High,180,7,173,0,No survivors,COM,Accident,Mt. San Pietro - Petreto-Bicchisano - Corsica ...,France,ENR,1981-12-01,41.7588889,8.9916667,Bad Visibility by Night
39,Aeroflot Flight 3352 involving a Tupolev Tu-1...,Extremely High,178,5,169,4,Some survivors,COM,Accident,Omsk - Russia,Russia,LDG,1984-10-11,54.9666667,73.3833333,Bad Visibility by Night
40,Aeroflot/Moldovia (CCCP-65816) involving a Tu...,Extremely High,178,13,165,0,No survivors,COM,Accident,Saykyn - Kazakhstan,Kazakhstan,ENR,1979-08-11,48.8125,46.7636111,Bad Visibility by Night
41,British Airways Flight 476 and involving a Ha...,Extremely High,177,14,162,1,No survivors,COM,Accident,Vrbovec - Croatia,Croatia,ENR,1976-09-10,45.8839523,16.416766,Bad Visibility by Night
42,Surinam Airways Flight 764 involving a Dougla...,Extremely High,176,9,167,0,No survivors,COM,Accident,Paramaribo - Surinam,Surinam,APR,1989-06-07,5.823201,-55.16788,Bad Visibility by Day
43,Nigeria Airways (JY-ADO) involving a Boeing 7...,Extremely High,176,6,170,0,Some survivors,COM,Accident,Kano - Nigeria,Nigeria,LDG,1973-01-22,12,8.516667,Bad Visibility by Day
44,Aeroflot Flight 217 involving a Ilyushin Il-6...,Extremely High,174,10,164,0,No survivors,COM,Accident,Moscow - Russia,Russia,APR,1972-10-13,55.755826,37.6173,Bad Visibility by Day
45,Cubana de Aviación Flight 9646 involving a Il...,Extremely High,171,11,115,45,No survivors,COM,Accident,Havana - Cuba,Cuba,ICL,1989-09-03,23.1168,-82.388557,Bad Visibility by Day
46,Pulkovo Flight 612 involving a Tupolev Tu-154...,Extremely High,170,10,160,0,No survivors,COM,Accident,Novoselivka - Donetsk Obl. - Ukraine,Ukraine,ENR,2006-08-22,49.0702778,37.6913889,Bad Visibility by Night
47,Union de Transportes Aériens Flight 772 invol...,Extremely High,170,14,156,0,No survivors,INB,Attack,Tenere - Niger,Niger,ENR,1989-19-09,18.9546137,10.9134609,Bad Visibility by Night
48,Kenya Airways Flight 431 involving a Airbus A...,Extremely High,169,10,159,0,Some survivors,COM,Accident,Gulf of Guinea - Cote d'Ivoire,Cote d'Ivoire,ENR,2000-01-30,3.7355442,3.743509,Bad Visibility by Night
49,Caspian Airlines Flight 7908 involving a Tupo...,Extremely High,168,12,156,0,No survivors,COM,Accident,Qazvin - Iran,Iran,ENR,2009-07-15,36.266819,50.003811,Bad Visibility by Night
50,Pakistan International Airlines Flight 268 in...,Extremely High,167,12,155,0,No survivors,COM,Accident,Kathmandu - Nepal,Nepal,APR,1992-09-28,27.7,85.3333333,Bad Visibility by Night
51,Mexicana Flight 940 involving a Boeing 727-26...,Extremely High,167,8,159,0,No survivors,COM,Accident,Sierra Madre Oriental Mountains - Mexico,Mexico,ENR,1986-03-31,-100.4233685,-100.4233685,Bad Visibility by Night
52,Aeroflot Flight 4227 involving a Tupolev Tu-1...,Extremely High,166,10,156,0,No survivors,COM,Accident,Almaty - Kazakhstan,Kazakhstan,ENR,1890-07-08,43.255058,76.912628,Bad Visibility by Night
53,Dana Air Flight 992 involving a McDonnell Dou...,Extremely High,163,6,147,10,No survivors,COM,Accident,Lagos - Nigeria,Nigeria,APR,2012-06-03,6.441158,3.417977,Bad Visibility by Night
54,All Nippon Airways Flight 58 and involving a ...,Extremely High,162,7,155,0,One survivor,COM,Accident,Shizukuishi - Japan,Japan,ENR,1971-07-30,39.6962875,140.9757756,Bad Visibility by Night
55,West Caribbean Airways Flight 708 involving a...,Extremely High,160,8,152,0,No survivors,COM,Accident,Machiques - Venezuela,Venezuela,ENR,2005-08-16,10.06592,-72.551872,Bad Visibility by Night
56,China Northwest Airlines Flight 2303 involvin...,Extremely High,150,14,146,0,No survivors,COM,Accident,Xian - China,China,ENR,1984-06-06,34.341568,108.940175,Bad Visibility by Night
57,American Airlines Flight 965 involving a Boei...,Extremely High,159,8,151,0,Some survivors,COM,Accident,Buga - Colombia,Colombia,APR,1995-12-20,3.9,-76.3,Bad Visibility by Night

Nice neat data! Let's make some column headings.

We first store the unique values in the fist column of the data in a list.

In [14]:
column_headers = data[0].unique().tolist() # Get the data again
column_headers

['Incident',
 'Casualties',
 'Total Dead',
 'Crew',
 'Passengers',
 'Ground',
 'Notes',
 'Type',
 'Reason',
 'Location',
 'Country',
 'Phase',
 'Date',
 'Latitude',
 'Longitude',
 'Circumstances']

Looks fine. Then we use this list to assign column names for the master file.

In [16]:
master.columns = column_headers # We supply it with a list of the same length

In [17]:
master.head() #done!

,Incident,Casualties,Total Dead,Crew,Passengers,Ground,Notes,Type,Reason,Location,Country,Phase,Date,Latitude,Longitude,Circumstances
0,American Airlines Flight 11 involving a Boein...,Extremely High,1692,11,81,1600,No survivors,INH,Attack,New York - New York - US,US,ENR,2001-09-11,40.7143528,-74.0059731,Good Visibility by Day
1,United Airlines Flight 175 involving a Boeing...,Extremely High,965,9,56,900,No survivors,INH,Attack,New York - New York - US,USA,ENR,2001-09-11,40.7143528,-74.0059731,Good Visibility by Day
2,Pan Am Flight 1736 and KLM Flight 4805 involv...,Extremely High,583,23,560,0,Some survivors,COM,Accident,Tenerife - Spain,Spain,TOF,1977-03-27,28.2915637,-16.6291304,Bad Visibility by Day
3,Japan Airlines Flight 123 involving a Beoing ...,Extremely High,520,15,505,0,Some survivors,COM,Accident,Ueno - Japan,Japan,ENR,1985-08-12,35.7089461,139.7742683,Bad Visibility by Night
4,Saudi Arabian Flight 763 and involving a Boei...,Extremely High,349,33,316,0,No survivors,,Accident,Charkhi Dadri - India,India,ENR,1996-11-12,28.6,76.2667,Bad Visibility by Night